// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihuakikekwlcfgvnrfic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodWFraWtla3dsY2Zndm5yZmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDk2NjcsImV4cCI6MjA2MDc4NTY2N30.jMX5L7isN00-togb2GrvucmE_hz8RRiK_84jy3uGUhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);